[tool.black]
target-version = ["py38"]

[tool.isort]
line_length = 88
force_grid_wrap = 0
multi_line_output = 3
use_parentheses = true
combine_as_imports = true
known_first_party = "gh"
known_third_party = "pytest, recommonmark"
include_trailing_comma = true
lines_after_imports = 2
