AWSTemplateFormatVersion: '2010-09-09'
Description: S3DB Converter

Parameters:
  PythonVersion:
    Type: String
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String
  S3DBBucket:
    Type: String
  S3DBProdPrefix:
    Type: String
  S3DBBucketSNS:
    Type: String
  S3DBBucketSNSFilter:
    Type: String

Resources:
  S3DBBucketSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt LiveJobSQS.Arn
      FilterPolicy: !Ref S3DBBucketSNSFilter
      Protocol: sqs
      TopicArn: !Ref S3DBBucketSNS

  LiveJobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  LiveJobSQS:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 86400  # 24 hr
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt LiveJobDLQ.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 3000

  LiveJobSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt LiveJobSQS.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref S3DBBucketSNS
      Queues:
        - !Ref LiveJobSQS

  SingleJobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  SingleJobSQS:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 86400  # 24 hr
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SingleJobDLQ.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 3000

  BatchJobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  BatchJobSQS:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 86400  # 24 hr
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BatchJobDLQ.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 3000

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: !Sub /${AWS::StackName}/
      Policies:
        - PolicyName: LambdaFunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - s3:ListBucket
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${S3DBBucket}
              - Action:
                  - s3:GetObject*
                  - s3:PutObject*
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${S3DBBucket}/*
              - Action:
                  - sqs:ReceiveMessage
                  - sqs:SendMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Effect: Allow
                Resource:
                  - !GetAtt SingleJobSQS.Arn
                  - !GetAtt BatchJobSQS.Arn
                  - !GetAtt LiveJobSQS.Arn

  RequestGeneratorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Description: A Lambda function to generate requests.
      Handler: lambdas/request_generator.lambda_handler
      Environment:
        Variables:
          SINGLE_JOB_SQS_URL: !Ref SingleJobSQS
          BATCH_JOB_SQS_URL: !Ref BatchJobSQS
      MemorySize: 512
      Role: !GetAtt LambdaFunctionRole.Arn
      Runtime: !Ref PythonVersion
      Timeout: 900  # 15 mins

  SingleJobRequestHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Description: A Lambda function to handle requests.
      Handler: lambdas/request_handler.lambda_handler
      MemorySize: 2048
      Role: !GetAtt LambdaFunctionRole.Arn
      Runtime: !Ref PythonVersion
      Timeout: 900  # 15 mins

  SingleJobRequestHandlerEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1  # max: 10
      Enabled: true
      EventSourceArn: !GetAtt SingleJobSQS.Arn
      FunctionName: !GetAtt SingleJobRequestHandlerFunction.Arn

  BatchJobRequestHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Description: A Lambda function to handle requests.
      Handler: lambdas/request_handler.lambda_handler
      MemorySize: 10240
      Role: !GetAtt LambdaFunctionRole.Arn
      Runtime: !Ref PythonVersion
      Timeout: 900  # 15 mins

  BatchJobRequestHandlerEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1  # max: 10
      Enabled: true
      EventSourceArn: !GetAtt BatchJobSQS.Arn
      FunctionName: !GetAtt BatchJobRequestHandlerFunction.Arn

  ProdListenerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Description: A Lambda function to listen to prod events.
      Handler: lambdas/prod_listener.lambda_handler
      Environment:
        Variables:
          SINGLE_JOB_SQS_URL: !Ref SingleJobSQS
      MemorySize: 128
      Role: !GetAtt LambdaFunctionRole.Arn
      Runtime: !Ref PythonVersion
      Timeout: 30

  ProdListenerEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1  # max: 10
      Enabled: true
      EventSourceArn: !GetAtt LiveJobSQS.Arn
      FunctionName: !GetAtt ProdListenerFunction.Arn

Outputs:
  RequestGeneratorFunctionName:
    Value: !Ref RequestGeneratorFunction
